max_width = 120
comment_width = 100
wrap_comments = false
reorder_imports = true
format_code_in_doc_comments = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
overflow_delimited_expr = true
trailing_comma = "Never"
fn_params_layout = "Compressed"
struct_lit_width = 32
style_edition = "2024"
